controllers:
  admittance_v0:
    filter00_a:
    - 1.0
    filter00_b:
    - 0.0
    filter01_a:
    - 1.0
    - -1.9480639384933955
    - 0.9480639384933955
    filter01_b:
    - 0.0
    - 2.095907740096159e-05
    - 2.0589771804302437e-05
    scale_output: 1
    type: integral
