controllers:
  admittance_v1:
    filter00_a:
    - 1.0
    filter00_b:
    - 0.0
    filter01_a:
    - 1.0
    - -1.9697987854661236
    - 0.9697987854661235
    filter01_b:
    - 0.0
    - 5.27923023962984e-06
    - 5.225540033126919e-06
    scale_output: 1
    type: integral
