joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
 
# Command controllers
j1:
  type: effort_controllers/JointPositionController
  joint: j1
  pid: {p: 100.0, i: 0.01, d: 10.0}
j2:
  type: effort_controllers/JointPositionController
  joint: j2
  pid: {p: 100.0, i: 0.01, d: 10.0}
j3:
  type: effort_controllers/JointPositionController
  joint: j3
  pid: {p: 100.0, i: 0.01, d: 10.0}
j4:
  type: effort_controllers/JointPositionController
  joint: j4
  pid: {p: 100.0, i: 0.0, d: 10.0}
j5:
  type: effort_controllers/JointPositionController
  joint: j5
  pid: {p: 100.0, i: 0.01, d: 10.0}
j6:
  type: effort_controllers/JointPositionController
  joint: j6
  pid: {p: 100.0, i: 0.01, d: 10.0}

position_trajectory_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6

  constraints:
    # Default is 0
    goal_time: 0.1
    # Default is 0.01
    stopped_velocity_tolerance: 0.01
    j1:
      trajectory: 0
      goal: 0.01
    j2:
      trajectory: 0
      goal: 0.01
    j3:
      trajectory: 0
      goal: 0.01
    j4:
      trajectory: 0
      goal: 0.01
    j5:
      trajectory: 0
      goal: 0.01
    j6:
      trajectory: 0
      goal: 0.01
