joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
 
# Command controllers
j1:
  type: position_controllers/JointPositionController
  joint: j1
j2:
  type: position_controllers/JointPositionController
  joint: j2
j3:
  type: position_controllers/JointPositionController
  joint: j3
j4:
  type: position_controllers/JointPositionController
  joint: j4
j5:
  type: position_controllers/JointPositionController
  joint: j5
j6:
  type: position_controllers/JointPositionController
  joint: j6

gazebo_ros_control:
  pid_gains:
    j1: {p: 100.0, i: 0.01, d: 10.0}
    j2: {p: 100.0, i: 0.01, d: 10.0}
    j3: {p: 100.0, i: 0.01, d: 10.0}
    j4: {p: 100.0, i: 0.01, d: 10.0}
    j5: {p: 100.0, i: 0.01, d: 10.0}
    j6: {p: 100.0, i: 0.01, d: 10.0}
