fir_siso:
  super:
    L:
    - 7.680093559598623e-05
    - 0.00013393001500590116
    - 0.0002157966988694689
    - 0.0002823935064112764
    - 0.0003764771227289948
    - 0.00045343571447814773
    - 0.0005518235001828316
    - 0.0006361873202763824
    - 0.0007381699094446372
    - 0.000817666787843893
    - 0.0009089536430045148
    - 0.0009784031406049364
    - 0.001059602803855946
    - 0.0011184486704831577
    - 0.0011881907267280634
    - 0.001234754189374209
    - 0.0012903273215849043
    - 0.0013222048166486064
    - 0.0013640068692285854
    - 0.0013845469692232108
    - 0.0014168266390789128
    - 0.0014296308237182237
    - 0.0014549141297247326
    - 0.001461374376628122
    - 0.0014804466675163042
    - 0.0014809402590647651
    - 0.0014941154416756542
    - 0.0014885847571030574
    - 0.0014950954759733563
    - 0.001482397300799066
    - 0.0014812852472161177
    - 0.001460960966233874
    - 0.001452573244435815
    - 0.0014256783210480463
    - 0.0014115532521836766
    - 0.001379977324989796
    - 0.0013620103468258938
    - 0.0013274833690095358
    - 0.0013073513516356388
    - 0.0012715109502505057
    - 0.0012506185289934265
    - 0.0012145681781227451
    - 0.0011936797216761089
    - 0.0011578008239521336
    - 0.0011370550388531888
    - 0.0011012975406529259
    - 0.0010805835288457165
    - 0.001044713922818817
    - 0.001023707352645268
    - 0.00098740751961158
    - 0.0009658046404708364
    - 0.0009288495975600477
    - 0.0009065293812340231
    - 0.0008689191389314778
    - 0.0008460944176995268
    - 0.0008081970387642281
    - 0.0007852999958242828
    - 0.0007477080146113608
    - 0.00072541332758576
    - 0.0006888572480990076
    - 0.000667950241914702
    - 0.0006332071532451182
    - 0.0006144593768801553
    - 0.0005822196554009224
    - 0.0005662801730609696
    - 0.0005370973605777173
    - 0.0005244112422883983
    - 0.0004986339871824948
    - 0.0004893901425275368
    - 0.0004670556920158711
    - 0.00046115162073209954
    - 0.00044199183888455105
    - 0.0004390208974184648
    - 0.000422520256062696
    - 0.00042185387266298753
    - 0.00040733597731603814
    - 0.0004082893000896435
    - 0.00039508127003081166
    - 0.00039701212891724263
    - 0.00038456825149622316
    - 0.00038702651359411104
    - 0.00037497801072439055
    - 0.0003777144340413174
    - 0.00036585631138207774
    - 0.00036873039108233855
    - 0.0003569709756134325
    - 0.0003599050001195267
    - 0.0003481461921255717
    - 0.0003509993759563155
    - 0.0003390820349831164
    - 0.00034164310283784873
    - 0.0003293352494328108
    - 0.0003313575452319585
    - 0.00031840754842853126
    - 0.0003196859511502066
    - 0.00030593697061111663
    - 0.00030636140161974896
    - 0.0002917910164555556
    - 0.00029143000570860825
    - 0.0002761646250422284
    - 0.0002752178596123829
    - 0.00025952840682970445
    - 0.00025830085461279415
    - 0.0002424777835818551
    - 0.00024126519802754217
    - 0.0002255746775903575
    - 0.00022458838770082103
    - 0.00020919493647449274
    - 0.00020851598356326376
    - 0.00019345853636883498
    - 0.00019308123688249973
    - 0.00017830412813107263
    - 0.00017814481496227267
    - 0.00016356393003117157
    - 0.00016354141142910095
    - 0.00014906646279832706
    - 0.00014912496798457126
    - 0.0001347218978016706
    - 0.0001348394100872131
    - 0.00012051128750122739
    - 0.00012070315257021795
    - 0.0001064670508459906
    - 0.0001067624968878045
    - 9.264516284379997e-05
    - 9.306331785788617e-05
    - 7.908278436670601e-05
    - 7.964663770647644e-05
    - 6.583518440712765e-05
    - 6.657505659388258e-05
    - 5.298392390522348e-05
    - 5.39512764155063e-05
    - 4.065862250451395e-05
    - 4.195524942601767e-05
    - 2.9045807060827416e-05
    - 3.0765644129080384e-05
    - 1.8325373636319067e-05
    - 2.0539718770833923e-05
    - 8.607581063787095e-06
    - 1.1330129478756703e-05
    - -1.1143638322323117e-07
    - 3.0616216372145006e-06
    - -7.956184250222684e-06
    - -4.432162610496506e-06
    - -1.5130490242246117e-05
    - -1.1338652630639415e-05
    - -2.179260091742881e-05
    - -1.7775911616752282e-05
    - -2.799166500084261e-05
    - -2.3723121331110103e-05
    - -3.3637597518569274e-05
    - -2.903143517672225e-05
    - -3.8546150570275086e-05
    - -3.3498435514427334e-05
    - -4.250276979492099e-05
    - -3.692791890046603e-05
    - -4.537982757222453e-05
    - -3.924572414426261e-05
    - -4.7137358171469954e-05
    - -4.0476710589415946e-05
    - -4.7853163394441244e-05
    - -4.069879993853374e-05
    - -4.758264902588839e-05
    - -3.994382533870343e-05
    - -4.629867175731285e-05
    - -3.810675888348234e-05
    - -4.383769449071947e-05
    - -3.4986410467591604e-05
    - -3.999382839318382e-05
    - -3.0382545275048812e-05
    - -3.4601440416134114e-05
    - -2.4236638292252708e-05
    - -2.7749489031888194e-05
    - -1.67514615324764e-05
    - -1.9765888970952255e-05
    - -8.433176308349722e-06
    - -1.126353255923337e-05
    - 4.083144017898012e-08
    - -2.9544535147606097e-06
    - 8.004560990663323e-06
    - 4.563631201775479e-06
    - 1.4961521128585708e-05
    - 1.0918041667836224e-05
    - 2.0663334372571398e-05
    - 1.5963872905629045e-05
    - 2.5029964143841472e-05
    - 1.9630531947184167e-05
    - 2.794572374587669e-05
    - 2.174822251303134e-05
    - 2.9146211309491388e-05
    - 2.1915369747504206e-05
    - 2.8148114690010126e-05
    - 1.964298193928096e-05
    - 2.447997391875968e-05
    - 1.4570664835166884e-05
    - 1.8025962566933096e-05
    - 6.885764448325906e-06
    - 9.334189494809034e-06
    - -2.4386718228319216e-06
    - -2.3954770264577334e-07
    - -1.1694155752873176e-05
    - -8.703988712836083e-06
    - -1.884098500921221e-05
    - -1.4096646308979905e-05
    - -2.2137764925574584e-05
    - -1.5119697417408984e-05
    - -2.0836127497205835e-05
    - -1.1673332015013772e-05
    - -1.554907824293778e-05
    - -5.001908513983307e-06
    - -8.001683007460527e-06
    - 2.7668372781170395e-06
    - -5.86108592445131e-07
    - 9.28773505032185e-06
    - 4.631662510242882e-06
    - 1.2830354309464921e-05
    - 6.441728982115406e-06
    - 1.2772989270140868e-05
    - 4.744792750817627e-06
    - 9.712982288509479e-06
    - 7.07642827390212e-07
    - 5.0787609768662795e-06
    - -3.990129285287293e-06
    - 6.843517551182449e-07
    - -7.5656114310447645e-06
    - -1.6809845905520504e-06
    - -8.516120011948023e-06
    - -1.2522207705219906e-06
    - -6.685607027934308e-06
    - 1.5240731926961509e-06
    - -3.39672236346952e-06
    - 4.749837040554386e-06
    - -6.256398583153868e-07
    - 6.453748527333377e-06
    - -5.7180811097863576e-08
    - 5.483781826320929e-06
    - -2.339705137409489e-06
    - 2.254233163973918e-06
    - -5.367207524024451e-06
    - 2.7674085535298574e-07
    - -4.970622745567677e-06
    - 2.76030821217058e-06
    - -1.6155979865615737e-06
    - 5.063835766633354e-06
    - -1.2519991645891688e-06
    - 2.5118540214294313e-06
    - -4.443361453944178e-06
    - 1.1490381027343084e-06
    - -1.9162397844500628e-06
    - 3.852003667748205e-06
    - -1.6680094405475902e-06
    - -6.521594281466809e-07
    - 7.617851658441219e-07
    - -2.4313843830841295e-07
    - 3.144270148680165e-08
    - -1.2078308032388983e-09
    - 1.5763186916919657e-11
    MB2:
    - 0.0
    - 0.007210512110597098
    - 0.001975969969547547
    - -0.005496642560538078
    - -0.01613040984097759
    - -0.020936841886174996
    - -0.026576780314148497
    - -0.027083143661056415
    - -0.028410365538715263
    - -0.02611364742570926
    - -0.02627902754129247
    - -0.02289716295152168
    - -0.02097619838382317
    - -0.015569890114840973
    - -0.012461236726710859
    - -0.006787037778210839
    - -0.0040413804862499125
    - 0.0008399800254465656
    - 0.002850717215823813
    - 0.007227198431256361
    - 0.008844574731190151
    - 0.012510093443938566
    - 0.013042695392561164
    - 0.015294038979518261
    - 0.014384060887399505
    - 0.015349786857785881
    - 0.013476122745308669
    - 0.01380238562379469
    - 0.011555162894928202
    - 0.01168598834760045
    - 0.009451238190215434
    - 0.009775534309215857
    - 0.007885876588101734
    - 0.008610912657026931
    - 0.007073619047305045
    - 0.008005635123979477
    - 0.006507959058588891
    - 0.007285788829855415
    - 0.00551018868191247
    - 0.005946450784653702
    - 0.003835559207189032
    - 0.00394546902275239
    - 0.0015670986408025667
    - 0.001465572643346312
    - -0.0010287742796106017
    - -0.0011494101263750875
    - -0.003554413117386121
    - -0.0034991668096698916
    - -0.005670627532635281
    - -0.0053476941289431965
    - -0.007229216383373635
    - -0.006618782311642923
    - -0.008219780394709192
    - -0.007358486821679819
    - -0.008739727458157029
    - -0.007698992034601733
    - -0.008952484617633427
    - -0.00784560029375066
    - -0.0090723007211613
    - -0.007991411059508187
    - -0.0092709932185524
    - -0.008275456948663891
    - -0.009651151224293237
    - -0.008762663928725552
    - -0.01024155946691388
    - -0.009443628614153363
    - -0.010995798572988148
    - -0.010248219935881715
    - -0.011822703269185417
    - -0.011074664377224281
    - -0.012617113585827563
    - -0.011808916172513641
    - -0.013261245625088116
    - -0.012335066966948697
    - -0.013641084144241011
    - -0.012550414707049392
    - -0.013670511701546264
    - -0.012387041218925015
    - -0.013311238939145603
    - -0.011845414614384988
    - -0.012597746164223107
    - -0.010991232325756769
    - -0.011631557306022692
    - -0.009950819935911955
    - -0.010555952375846871
    - -0.008873535673352381
    - -0.009505805614476934
    - -0.007873844753458457
    - -0.008573640629529651
    - -0.007017015867408622
    - -0.007787832242240196
    - -0.006297119435743284
    - -0.0071166352748212175
    - -0.0056629558504007835
    - -0.006502001124504655
    - -0.0050562482294951305
    - -0.005894623580652021
    - -0.004450281407494448
    - -0.005289926352810342
    - -0.0038587173074122565
    - -0.004724482726773253
    - -0.0033356502295305204
    - -0.004256523556703041
    - -0.002940003319068671
    - -0.003945278736125445
    - -0.002717405023081411
    - -0.0038119821480574736
    - -0.0026676164131495678
    - -0.003833439494556833
    - -0.002747417494506673
    - -0.0039479964414323755
    - -0.0028793561734813365
    - -0.004076339317777585
    - -0.0029898027938171177
    - -0.004151754197766173
    - -0.0030248484310410675
    - -0.004141838226734521
    - -0.002970124972451059
    - -0.004046257846448817
    - -0.0028425269879299685
    - -0.00389371772826273
    - -0.0026761430586302766
    - -0.0037211277619844927
    - -0.0025045621956465594
    - -0.003555438728892379
    - -0.0023488087186319916
    - -0.003409629552384066
    - -0.0022125856209142367
    - -0.003280686299761055
    - -0.0020917359657016826
    - -0.003164277085874372
    - -0.001983393698060101
    - -0.003059604297314234
    - -0.001887355896199218
    - -0.002974194605617065
    - -0.0018155579248714919
    - -0.0029164932553882622
    - -0.0017731616182643233
    - -0.0028884215275918456
    - -0.0017559473383740116
    - -0.0028771773497749224
    - -0.0017451056559082685
    - -0.002856845668373913
    - -0.0017116416667656703
    - -0.0028003248702942523
    - -0.0016287000795348317
    - -0.0026881028188603853
    - -0.0014892066124390735
    - -0.0025243939940123644
    - -0.0013099112022902926
    - -0.002336999005807915
    - -0.001126533756656278
    - -0.002165863263383374
    - -0.0009771892159543358
    - -0.0020410576801705824
    - -0.0008836624319049064
    - -0.0019773063481454394
    - -0.0008450221766337699
    - -0.0019563822637204617
    - -0.0008363459406625852
    - -0.0019487033370627167
    - -0.0008215006298754975
    - -0.001919646710466497
    - -0.0007771723979733779
    - -0.0018570436285047236
    - -0.0007033051898539731
    - -0.00177662642996104
    - -0.0006286235716083952
    - -0.0017139799121110265
    - -0.000585363855645024
    - -0.0016934521142822167
    - -0.0005915046734814214
    - -0.0017199994377536784
    - -0.0006266486715883589
    - -0.0017538701075397085
    - -0.0006451543396808677
    - -0.0017367261742056313
    - -0.000582067794340845
    - -0.001609827613099505
    - -0.000389446270340668
    - -0.0013479590217113243
    - -6.874304719452391e-05
    - -0.0009781305314133632
    - 0.000330234574561059
    - -0.0005679218450682534
    - 0.0007299261738587289
    - -0.000195447521452037
    - 0.0010629026755161572
    - 9.637375449044296e-05
    - 0.0013116707793697222
    - 0.0003125220245016057
    - 0.001510292071164314
    - 0.0005117367402963367
    - 0.0017208534034694536
    - 0.0007497956116986556
    - 0.001986519770585668
    - 0.0010380075887446018
    - 0.0022768098050222896
    - 0.0013060374618005784
    - 0.0024782850406527513
    - 0.001410564105516656
    - 0.0024346707649466866
    - 0.001187097810226295
    - 0.002008614514121375
    - 0.000553630677157017
    - 0.0011804432147856363
    - -0.00042935615621393294
    - 9.353712071500991e-05
    - -0.0015451414752676055
    - -0.0009686217911216769
    - -0.002465967877142409
    - -0.0016828759731820735
    - -0.002907592897077842
    - -0.0018116647369839697
    - -0.0027089448726020605
    - -0.0013130820622224131
    - -0.0019391739770186689
    - -0.00035854744529561323
    - -0.0008631598502804579
    - 0.0007502689068708207
    - 0.00018633603471411694
    - 0.0016508754809298671
    - 0.0008862779526631521
    - 0.00209363081545309
    - 0.0010662086828076484
    - 0.0020082571128790016
    - 0.0007171547286040024
    - 0.0014170208309841033
    - -3.365604617513502e-05
    - 0.0005566098787874414
    - -0.0009049593374199187
    - -0.00022547120099031595
    - -0.0014857236595505734
    - -0.0005639739041209269
    - -0.001511282378761298
    - -0.00032288715845056864
    - -0.0010092734953732019
    - 0.0003785319960911655
    - -0.00015896938882060266
    - 0.0011854897293197694
    - 0.00045697133821231533
    - 0.0013144783863900194
    - -3.5313384897702014e-05
    - 0.0003324410012436908
    - -0.0010362515919041786
    - -0.0003301507194898014
    - -0.0008845440827811769
    - 0.0005487589070735387
    - 0.000188821494565128
    - 0.0007402264082978047
    - -0.0005035948122740599
    - -0.0002238252236199442
    - 0.00018960156773036816
    - -1.8561273143521236e-05
    - -4.567370822370015e-06
    - 1.273163392355363e-07
    T: 256
    nu: 1
    ny: 1
