data_board:
  layout: [1, 2]
  number_store_points: 5000
  time_window_sec: 40

  handles:
    - [0, "/debugger/cartesian_force_measurement", 0]
    - [0, "/debugger/cartesian_force_measurement", 1]
    - [0, "/debugger/cartesian_force_measurement", 2]
    - [0, "/debugger/cartesian_command", 2]

    - [1, "/debugger/joint_command", 1]
    - [1, "/debugger/joint_measure", 1]
  
  axes_configs:
    yranges:
      - [0, [-2, 40]]
      - [1, [-0.1, 0.1]]

