data_board:
  layout: [1, 2]
  number_store_points: 5000
  time_window_sec: 120

  handles:
    - [0, "/debugger/cartesian_force_measurement", 0]
    - [0, "/debugger/cartesian_force_measurement", 1]
    - [1, "/debugger/cartesian_command", 2]
  
  axes_configs:
    yranges:
      - [0, [-2, 2]]
      - [1, [-0.2, 0.2]]

