controllers:
  integral0_0:
    filter00_a:
    - 1.0
    - -1.0
    filter00_b:
    - -0.009600000000000053
    - 0
    filter01_a:
    - 1.0
    - -1.0
    filter01_b:
    - 0.009600000000000053
    - 0
    scale_output: 0.001
    type: integral
