controllers:
  integral0_0:
    filter00_a:
    - 1.0
    - -1.0
    filter00_b:
    - -0.0010000000000000009
    - 0.0008399999999999519
    filter01_a:
    - 1.0
    - -1.0
    filter01_b:
    - 0.0010000000000000009
    - -0.0008399999999999519
    type: integral
